title: "AbODE: Ab initio antibody design using conjoined ODEs"
description: In International Conference on Machine Learning (ICML), 2023
author: "Yogesh Verma<sup>1</sup>, Markus Heinonen<sup>1</sup>, Vikas Garg<sup>1,2</sup> <br> <sup>1</sup>  Aalto University , <sup>2</sup>  YaiYai Ltd <br> yogesh.verma@aalto.fi, markus.o.heinonen@aalto.fi, vikas.garg@aalto.fi"
email: yogesh.verma@aalto.fi
theme: jekyll-theme-cayman # << Set the Cayman theme!
plugins:
  - jekyll-feed
