title: "AbODE: Ab initio antibody design using conjoined ODEs"
email: yogesh.verma@aalto.fi
description: In International Conference on Machine Learning (ICML), 2023
avatar: aaltologo.png
author: Yogesh Verma, Markus Heinonen, Vikas Garg
theme: jekyll-theme-cayman
