title: "AbODE: Ab initio antibody design using conjoined ODEs"
description: In International Conference on Machine Learning (ICML), 2023
author: Yogesh Verma, Markus Heinonen, Vikas Garg
email: yogesh.verma@aalto.fi
markdown: kramdown
theme: jekyll-theme-cayman # << Set the Cayman theme!
plugins:
  - jekyll-feed
