title: "AbODE: Ab initio antibody design using conjoined ODEs"
description: In International Conference on Machine Learning (ICML), 2023
author: Yogesh Verma, Markus Heinonen, Vikas Garg
email: yogesh.verma@aalto.fi, markus.o.heinonen@aalto.fi, vikas.garg@aalto.fi
theme: jekyll-theme-cayman
